module.exports = {
  URL_API: process.env.REACT_APP_URL_API,
  AES_KEY: process.env.REACT_APP_AES_KEY,
  AES_IV: process.env.REACT_APP_AES_IV,
  BASIC_AUTH_USERNAME: process.env.REACT_APP_BASIC_AUTH_USERNAME,
  BASIC_AUTH_PASSWORD: process.env.REACT_APP_BASIC_AUTH_PASSWORD,
};
